version: '3.8'

services:
    frankenphp:
        build: .
        entrypoint: php artisan octane:frankenphp --max-requests=1
        ports:
            - "80:8000"
        volumes:
            - .:/app

    composer:
        image: composer:2.2.21
        container_name: composer
        hostname: composer
        volumes:
            - ./:/app
        working_dir: /app
